### ISSUE TITLE
Small bugs in download_wiki script

### ISSUE THREAD

**Issue by nhatsmrt** [google-research/fool-me-twice#1]
[This line](https://github.com/google-research/fool-me-twice/blob/main/util/download_wiki.py#L23) should be `import os`.

I believe there should be prefix f for the string interpolation in [this line](https://github.com/google-research/fool-me-twice/blob/main/util/download_wiki.py#L94).

I can send a PR later to fix these.

**Comment by eisenjulian** [comment]
Good catch, and thanks for the fix. I merged the PR
