### ISSUE TITLE
Clarification on Firebase Hosting 

### ISSUE THREAD

**Issue by nhatsmrt** [google-research/fool-me-twice#3]
I followed the instructions in [this section](https://github.com/google-research/fool-me-twice#deploying-the-game-in-a-production-setting-on-a-server), but wasn't able to deploy the game; the page came out empty. I was able to run the game locally.

Here is what I did: inside `board`:
```
firebase init hosting  # using defaults for all of their prompts
firebase deploy --only hosting  # i have also tried without the flag.

npm run prestart
npm run build
npm run start
```

Am I doing anything wrong? E.g run the commands in the wrong directory

**Comment by nhatsmrt** [comment]
Nvm, I think the deployment should be more complicated than this. Closing this issue.

**Comment by eisenjulian** [comment]
I am happy to hear that's running smoothly locally, I think it should it be quite easy to run on firebase hosting from that point on, it's just that so far I used a different hosting solution. You probably want to do `npm run build` before running the firebase deploy command, and I am not sure if you need prestart/start. Can you double check that the build folder exists and that the firebase deploy command is pointing to it? If you make it work, we can add a section in the docs about it as well.

**Comment by nhatsmrt** [comment]
@eisenjulian I was able to deploy it via Firebase hosting now! Apparently I had to select the `build` directory instead of creating a new `public` directory. No wonder why they couldn't find the app's build files 😅
